/**
 * @moolox/web — Live Patch Preview Overlay (Feature: AI-005)
 *
 * Displays proposed structural sub-tree changes (`mutatedTree` / `patches`)
 * generated by the 3-Agent Core AI Loop (`ORC-001..013`) before committing
 * them to the active canvas and `projectStore`.
 *
 * Copyright © 2026 Moolox. All Rights Reserved.
 */

import React, { useEffect } from 'react';
import { type AgentResult } from '@moolox/ai';

export interface LivePatchPreviewProps {
  /** The pending proposal returned from the 3-Agent Core AI Loop (`AgentResult`) */
  proposal: AgentResult | null;
  /** Callback to confirm and merge proposed tree/patch into active canvas */
  onConfirmPatch: () => void;
  /** Callback to discard pending proposal without mutating canvas */
  onDiscardPatch: () => void;
}

export const LivePatchPreview: React.FC<LivePatchPreviewProps> = ({
  proposal,
  onConfirmPatch,
  onDiscardPatch,
}) => {
  // Global Enter / Esc listener for rapid patch confirmation
  useEffect(() => {
    if (!proposal) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        onConfirmPatch();
      } else if (e.key === 'Escape') {
        e.preventDefault();
        onDiscardPatch();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [proposal, onConfirmPatch, onDiscardPatch]);

  if (!proposal || !proposal.success) {
    return null;
  }

  const patchesCount = proposal.patches?.length || 0;

  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 w-full max-w-xl animate-slideUp">
      <div
        className="bg-gray-950 border-2 border-blue-500/80 rounded-2xl shadow-2xl p-4 text-xs text-gray-200 flex flex-col gap-3 backdrop-blur-md"
        role="alert"
        aria-label="Live Patch Proposal Review"
      >
        <div className="flex items-center justify-between border-b border-gray-800 pb-2.5">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-green-500 animate-pulse" />
            <span className="font-bold text-white text-sm">Proposed AI Canvas Mutation (`AI-005`)</span>
            <span className="px-2 py-0.5 rounded bg-blue-900/60 text-blue-300 font-mono text-[10px] border border-blue-800">
              {proposal.intent}
            </span>
          </div>
          <span className="text-gray-400 font-mono text-[11px]">
            {proposal.durationMs}ms | {proposal.tokensUsed} tokens
          </span>
        </div>

        <p className="text-gray-300 leading-relaxed text-[12px] bg-gray-900/80 p-3 rounded-xl border border-gray-800/80">
          {proposal.explanation || 'Structural layout updates generated and verified by 3-Agent Loop.'}
        </p>

        <div className="flex items-center justify-between text-[11px] font-mono text-gray-400">
          <span>
            Quality Gate: <span className="text-green-400 font-semibold">✓ WCAG 2.1 AA & Zero-Hex Passed</span>
          </span>
          <span>
            Structural Deltas: <span className="text-purple-400 font-semibold">{patchesCount} patch ops</span>
          </span>
        </div>

        <div className="flex items-center justify-end gap-3 pt-2 border-t border-gray-800/80">
          <button
            type="button"
            onClick={onDiscardPatch}
            className="px-4 py-2 rounded-lg bg-gray-900 hover:bg-gray-800 text-gray-300 font-semibold transition border border-gray-800"
          >
            Discard (`Esc`)
          </button>
          <button
            type="button"
            onClick={onConfirmPatch}
            className="px-5 py-2 rounded-lg bg-green-600 hover:bg-green-500 text-white font-bold transition shadow-lg flex items-center gap-1.5"
          >
            <span>Apply to Canvas</span>
            <kbd className="px-1.5 py-0.5 rounded bg-green-700 font-mono text-[10px]">Cmd+Enter</kbd>
          </button>
        </div>
      </div>
    </div>
  );
};
