/**
 * @moolox/ai — Unified Agent Interface & Pipeline Types (Feature: ORC-001)
 *
 * Standardized TypeScript interface contracts ensuring all 12+ AI agents plug
 * deterministically into the 3-Agent Core AI Loop (`Router -> Generator -> Linter`).
 *
 * Copyright © 2026 Moolox. All Rights Reserved.
 */

import { type IASTNode, type IW3CTokenMap } from '@moolox/types';
import { type ASTPatchOperation } from '@moolox/ast-core';

/**
 * Moolox AI Prompt Intent Categories classification.
 */
export type AIIntentCategory =
  | 'ADD_SECTION'
  | 'UPDATE_STYLE'
  | 'REFACTOR_SUBTREE'
  | 'ANSWER_QUESTION'
  | 'UNKNOWN';

/**
 * Standardized context payload passed into any agent executor (`ORC-001`).
 */
export interface AgentContext {
  /** Raw user natural language instruction from Cmd+K bar (`AI-001`) */
  userPrompt: string;
  /** Active root AST sub-tree canvas (`IASTNode`) */
  astTree?: IASTNode | null;
  /** Currently selected or target node ID (`data-node-id`) */
  targetNodeId?: string | null;
  /** Active W3C design tokens map (`IW3CTokenMap`) for TKN-003 Zero-Hex Law */
  activeTokens?: IW3CTokenMap;
  /** Maximum token budget limit for context window slicing */
  tokenBudgetMax?: number;
  /** Additional key-value context variables */
  metadata?: Record<string, any>;
}

/**
 * Standardized execution result returned from any agent executor (`ORC-001`).
 */
export interface AgentResult {
  /** Whether the agent execution completed successfully */
  success: boolean;
  /** Classified intent (`ORC-002`) */
  intent?: AIIntentCategory;
  /** Target node ID resolved by router or mutated by generator */
  targetNodeId?: string | null;
  /** Pruned context slice generated by Haiku router (`ORC-002`) */
  prunedContextTree?: IASTNode | null;
  /** Fully mutated or generated canonical AST node tree (`ORC-003`) */
  mutatedTree?: IASTNode | null;
  /** Structural delta operations required to patch existing canvas (`AST-003`) */
  patches?: ASTPatchOperation[];
  /** Natural language response explanation or generated summary */
  explanation?: string;
  /** Whether the deterministic quality gate passed (`ORC-004`) */
  qualityGatePassed?: boolean;
  /** List of static quality or Zero-Hex linter violations caught during check */
  linterErrors?: string[];
  /** Total execution duration in milliseconds */
  durationMs: number;
  /** Estimated token consumption count */
  tokensUsed: number;
}

/**
 * Unified Agent Executor contract (`ORC-001`).
 * Every specialized agent (`HaikuRouter`, `SonnetGenerator`, `QualityGate`) implements this interface.
 */
export interface IAgentExecutor {
  /** Unique identifier of the agent (`haiku-router`, `sonnet-generator`, `static-linter`) */
  readonly agentId: string;
  /** Human-readable display title */
  readonly title: string;
  /**
   * Executes the agent workflow against the provided agent context.
   */
  execute(context: AgentContext): Promise<AgentResult>;
}
