/**
 * @moolox/tokens — Hardcoded Token Enforcement Rule Engine & Zero-Hex Law (TKN-003)
 *
 * Blocks ad-hoc hex strings (`#123456`) and arbitrary CSS values entered via inspector
 * or generated by AI prompt turns. Automatically maps raw color values to the nearest
 * canonical W3C design token (`color.accent.error`, `color.bg.primary`, etc.).
 *
 * Copyright © 2026 Moolox. All Rights Reserved.
 */

import { type IASTNode, type IW3CTokenMap } from '@moolox/types';
import { flattenTokenMap, tokenPathToCssVar } from './tailwind';

/**
 * A violation detected by the Zero-Hex Law rule engine.
 */
export interface TokenViolation {
  /** Node ID where the violation occurred */
  nodeId: string;
  /** Property or style key (`className`, `style.color`, etc.) */
  propertyKey: string;
  /** Raw forbidden value (`#ff0000`, `bg-[#123456]`) */
  rawValue: string;
  /** Suggested canonical token path replacement (`color.accent.error`) */
  suggestedTokenPath: string;
  /** Suggested CSS custom property (`--dios-color-accent-error`) */
  suggestedCssVar: string;
}

/**
 * Result of enforcing token resolution on a raw value.
 */
export interface TokenResolution {
  /** Resolved canonical token path (`color.accent.error`) */
  resolvedTokenPath: string;
  /** Resolved CSS variable name (`--dios-color-accent-error`) */
  resolvedCssVar: string;
  /** Whether the original value was an ad-hoc hex string that required auto-mapping */
  wasMapped: boolean;
}

/** Regex to detect hex color strings (`#fff`, `#ff0000`, `#1a1a2eaa`) or arbitrary Tailwind bracket hex (`bg-[#ff0000]`) */
const HEX_COLOR_REGEX = /(?:^|[\s[("'])(#[0-9a-fA-F]{3,8})(?:[\s\])"']|$)/;

/**
 * Resolves or auto-maps any raw color value (or ad-hoc hex string) to the nearest
 * canonical token inside `tokenMap`. Enforces the Zero-Hex Law (`TKN-003`).
 */
export function enforceTokenResolution(
  rawValue: string,
  tokenMap: IW3CTokenMap,
  fallbackTokenPath = 'color.accent.error',
  prefix = 'dios',
): TokenResolution {
  const inputTrimmed = rawValue.trim();

  // Check if it's already a CSS var (`var(--dios-color-bg-primary)` or `--dios-color-bg-primary`)
  if (inputTrimmed.startsWith('var(--') || inputTrimmed.startsWith('--')) {
    return {
      resolvedTokenPath: inputTrimmed,
      resolvedCssVar: inputTrimmed.startsWith('var(') ? inputTrimmed.slice(4, -1) : inputTrimmed,
      wasMapped: false,
    };
  }

  // Check if input contains a hex color
  const match = HEX_COLOR_REGEX.exec(inputTrimmed);
  if (!match || !match[1]) {
    return {
      resolvedTokenPath: inputTrimmed,
      resolvedCssVar: inputTrimmed,
      wasMapped: false,
    };
  }

  const hexInput = normalizeHex(match[1]);
  const flatTokens = flattenTokenMap(tokenMap);

  let bestMatchPath = fallbackTokenPath;
  let minDistance = Number.POSITIVE_INFINITY;

  const inputRgb = hexToRgb(hexInput);

  if (inputRgb) {
    for (const [path, token] of Object.entries(flatTokens)) {
      if (token.type !== 'color' && !path.startsWith('color.')) continue;

      const tokenHex = normalizeHex(token.value);
      const tokenRgb = hexToRgb(tokenHex);
      if (!tokenRgb) continue;

      // Exact match check
      if (tokenHex.toLowerCase() === hexInput.toLowerCase()) {
        bestMatchPath = path;
        minDistance = 0;
        break;
      }

      // Euclidean RGB distance for finding nearest harmonious color token
      const distance = Math.sqrt(
        Math.pow(inputRgb.r - tokenRgb.r, 2) +
          Math.pow(inputRgb.g - tokenRgb.g, 2) +
          Math.pow(inputRgb.b - tokenRgb.b, 2),
      );

      if (distance < minDistance) {
        minDistance = distance;
        bestMatchPath = path;
      }
    }
  }

  const cssVar = tokenPathToCssVar(bestMatchPath, prefix);

  return {
    resolvedTokenPath: bestMatchPath,
    resolvedCssVar: cssVar,
    wasMapped: true,
  };
}

/**
 * Scans an `IASTNode` tree recursively for raw hex violations (`TKN-003`).
 */
export function validateNoRawHexOrAdhocValues(
  tree: IASTNode,
  tokenMap: IW3CTokenMap,
  prefix = 'dios',
): { valid: boolean; violations: TokenViolation[] } {
  const violations: TokenViolation[] = [];

  function scanNode(node: IASTNode) {
    if (!node) return;

    // Scan className prop
    const className = typeof node.props.className === 'string' ? node.props.className : '';
    if (className && HEX_COLOR_REGEX.test(className)) {
      const match = HEX_COLOR_REGEX.exec(className);
      if (match && match[1]) {
        const resolution = enforceTokenResolution(match[1], tokenMap, 'color.accent.error', prefix);
        violations.push({
          nodeId: node.nodeId,
          propertyKey: 'className',
          rawValue: match[1],
          suggestedTokenPath: resolution.resolvedTokenPath,
          suggestedCssVar: resolution.resolvedCssVar,
        });
      }
    }

    // Scan inline styles
    if (node.styles && typeof node.styles === 'object') {
      for (const [styleKey, styleVal] of Object.entries(node.styles)) {
        if (typeof styleVal === 'string' && HEX_COLOR_REGEX.test(styleVal)) {
          const match = HEX_COLOR_REGEX.exec(styleVal);
          if (match && match[1]) {
            const resolution = enforceTokenResolution(match[1], tokenMap, 'color.accent.error', prefix);
            violations.push({
              nodeId: node.nodeId,
              propertyKey: `style.${styleKey}`,
              rawValue: match[1],
              suggestedTokenPath: resolution.resolvedTokenPath,
              suggestedCssVar: resolution.resolvedCssVar,
            });
          }
        }
      }
    }

    if (node.children) {
      for (const child of node.children) {
        scanNode(child);
      }
    }
  }

  scanNode(tree);

  return {
    valid: violations.length === 0,
    violations,
  };
}

/**
 * Automatically mutates any node containing ad-hoc hex values, replacing them
 * with resolved token variables or utility equivalents (`TKN-003`).
 */
export function sanitizeNodeTokens(node: IASTNode, tokenMap: IW3CTokenMap, prefix = 'dios'): IASTNode {
  const { valid } = validateNoRawHexOrAdhocValues(node, tokenMap, prefix);
  if (valid) return node;

  const newProps = { ...node.props };
  const newStyles = { ...node.styles };

  if (typeof newProps.className === 'string' && HEX_COLOR_REGEX.test(newProps.className)) {
    const match = HEX_COLOR_REGEX.exec(newProps.className);
    if (match && match[1]) {
      const resolution = enforceTokenResolution(match[1], tokenMap, 'color.accent.error', prefix);
      newProps.className = newProps.className.replace(
        match[1],
        `var(${resolution.resolvedCssVar})`,
      );
    }
  }

  if (newStyles && typeof newStyles === 'object') {
    for (const [key, val] of Object.entries(newStyles)) {
      if (typeof val === 'string' && HEX_COLOR_REGEX.test(val)) {
        const match = HEX_COLOR_REGEX.exec(val);
        if (match && match[1]) {
          const resolution = enforceTokenResolution(match[1], tokenMap, 'color.accent.error', prefix);
          newStyles[key] = `var(${resolution.resolvedCssVar})`;
        }
      }
    }
  }

  const newChildren = node.children
    ? node.children.map((child) => sanitizeNodeTokens(child, tokenMap, prefix))
    : undefined;

  return {
    nodeId: node.nodeId,
    type: node.type,
    props: newProps,
    styles: newStyles,
    children: newChildren,
  };
}

function normalizeHex(hex: string): string {
  let clean = hex.startsWith('#') ? hex.slice(1) : hex;
  if (clean.length === 3) {
    clean = clean[0]! + clean[0]! + clean[1]! + clean[1]! + clean[2]! + clean[2]!;
  }
  return '#' + clean.slice(0, 6);
}

function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const clean = normalizeHex(hex).slice(1);
  if (clean.length !== 6) return null;
  const num = Number.parseInt(clean, 16);
  if (Number.isNaN(num)) return null;
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}
